### PR TITLE
Implement QMLE for Linear State Space Model

### PR DESCRIPTION
**Pull request by onion213**
This PR implements new function named `qmle.linear_state_space_model`.
The function uses Kalman-Bucy filter and somputes QMLE for Linear State Space Model.

Some other functions are implemented as a part of this PR.
- classes: 
  - `yuima.state_space_model`: A class for state space model, extending `yuima.model`
  - `yuima.linear_state_space_model`: A class for linear state space model, extending `yuima.state_space_model`
- functions: 
  - `kalmanBucyFilter`: A function to compute Kalman-Bucy filter.
 
refer to: Kurisaki, M. (2023). Parameter estimation for ergodic linear SDEs from partial and discrete observations. Stat Inference Stoch Process, 26, 279-330.

### CODE REVIEW

**Review by makrisaki — CHANGES_REQUESTED** [review]
Warning occurred while building:
/yuima/man/yuima.state_space_model-class.Rd:40: unexpected section header '\author'
yuima/man/yuima.state_space_model-class.Rd:41: unexpected section header '\keyword'
yuima/man/yuima.state_space_model-class.Rd:42: unexpected END_OF_INPUT '

**Comment by onion213** [comment]
Thanks, I fixed it in https://github.com/yuimaproject/yuima/pull/4/commits/e6d8872db9b19086765ec22522bfde5c5250a6c0

> Warning occurred while building: /yuima/man/yuima.state_space_model-class.Rd:40: unexpected section header '\author' yuima/man/yuima.state_space_model-class.Rd:41: unexpected section header '\keyword' yuima/man/yuima.state_space_model-class.Rd:42: unexpected END_OF_INPUT '

**Review by makrisaki — CHANGES_REQUESTED** [review]
qmle does not work when diffusion is not square and rcpp=FALSE.

**Review by makrisaki — APPROVED** [review]
OK

**Pull request merged**
